// tooling/scripts/build-runtime.mjs
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as esbuild from 'esbuild';

const ROOT_DIR = path.resolve(process.cwd());
const RESOURCES_SRC = path.join(ROOT_DIR, 'resources-src');
const OUTPUT_DIR = path.join(ROOT_DIR, '../resources/[trp-framework]');

/**
 * Builds a specific FiveM resource using esbuild and generates its fxmanifest.lua.
 *
 * @param {string} sourcePath Path to the resource's source folder (e.g., resources-src/core/kernel)
 */
async function buildResource(sourcePath) {
  const pkgPath = path.join(sourcePath, 'package.json');
  if (!fs.existsSync(pkgPath)) return;

  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  const rawName = pkg.name; // e.g., @trp/core-kernel
  const resourceName = rawName.startsWith('@trp/') ? rawName.replace('@trp/', '') : rawName;

  const srcServer = path.join(sourcePath, 'src/server/server.ts');
  const srcClient = path.join(sourcePath, 'src/client/client.ts');

  const hasServer = fs.existsSync(srcServer);
  const hasClient = fs.existsSync(srcClient);

  if (!hasServer && !hasClient) {
    console.warn(`[WARN] Skipping ${resourceName}: No valid entry points found.`);
    return;
  }

  const outDir = path.join(OUTPUT_DIR, resourceName);
  const distDir = path.join(outDir, 'dist');
  fs.mkdirSync(distDir, { recursive: true });

  const buildManifest = {
    server: false,
    client: false,
  };

  try {
    // Custom plugin to resolve pnpm workspace packages directly to their source
    const workspaceResolverPlugin = {
      name: 'workspace-resolver',
      setup(build) {
        build.onResolve({ filter: /^@trp\// }, (args) => {
          const pkgName = args.path.replace('@trp/', '');
          // Point directly to the TypeScript source file in the packages directory
          const sourcePath = path.join(ROOT_DIR, 'packages', pkgName, 'src', 'index.ts');
          return { path: sourcePath };
        });
      },
    };

    // 1. Build Server
    if (hasServer) {
      await esbuild.build({
        entryPoints: [srcServer],
        outfile: path.join(distDir, 'server.js'),
        bundle: true,
        target: 'node22',
        platform: 'node',
        format: 'cjs',
        minify: true,
        plugins: [workspaceResolverPlugin],
        external: ['dotenv', 'zod', 'ioredis', 'bullmq', 'postgres', 'drizzle-orm'], // Native external modules
      });
      buildManifest.server = true;
    }

    // 2. Build Client
    if (hasClient) {
      await esbuild.build({
        entryPoints: [srcClient],
        outfile: path.join(distDir, 'client.js'),
        bundle: true,
        target: 'es2022',
        platform: 'browser',
        format: 'iife',
        minify: true,
        plugins: [workspaceResolverPlugin],
      });
      buildManifest.client = true;
    }

    // 3. Generate Manifest
    generateManifest(outDir, buildManifest);

    console.log(`[SUCCESS] Built ${resourceName} -> ${outDir}`);
  } catch (err) {
    console.error(`[ERROR] Failed to build ${resourceName}`, err);
    process.exit(1);
  }
}

/**
 * Generates fxmanifest.lua based on architectural constraints.
 */
function generateManifest(outDir, manifestData) {
  const lines = [
    `-- TRP Framework: Generated by build-runtime.mjs`,
    `fx_version 'cerulean'`,
    `game 'gta5'`,
    ``,
  ];

  if (manifestData.server && !manifestData.client) {
    lines.push(`server_only 'yes'`);
    lines.push(``);
  }

  if (manifestData.server) {
    lines.push(`node_version '22'`);
    lines.push(`server_scripts {`);
    lines.push(`  'dist/server.js'`);
    lines.push(`}`);
    lines.push(``);
  }

  if (manifestData.client) {
    lines.push(`client_scripts {`);
    lines.push(`  'dist/client.js'`);
    lines.push(`}`);
    lines.push(``);
  }

  const manifestContent = lines.join('\n');
  const manifestPath = path.join(outDir, 'fxmanifest.lua');
  fs.writeFileSync(manifestPath, manifestContent);

  // 4. Build Validation (Step 5)
  if (!fs.existsSync(manifestPath) || fs.statSync(manifestPath).size === 0) {
    console.error(`[VALIDATION ERROR] Manifest missing or empty at ${manifestPath}`);
    process.exit(1);
  }
}

// Scrape categories (core, gameplay, etc.)
const categories = fs
  .readdirSync(RESOURCES_SRC, { withFileTypes: true })
  .filter((dirent) => dirent.isDirectory())
  .map((dirent) => dirent.name);

async function run() {
  console.log('🚀 Starting TRP Framework Runtime Build Phase...');

  for (const category of categories) {
    const categoryPath = path.join(RESOURCES_SRC, category);
    const resources = fs
      .readdirSync(categoryPath, { withFileTypes: true })
      .filter((dirent) => dirent.isDirectory())
      .map((dirent) => dirent.name);

    for (const resource of resources) {
      await buildResource(path.join(categoryPath, resource));
    }
  }

  console.log('✅ TRP Framework Build Complete.');
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
